2020-04-16 16:52:36.606 ERROR 2ed0xe2ck92tpk3j - DBInitialization - connectAndCreate - mydb, admin - Can't create database 'mydb'; database exists
{"message":"Can't create database 'mydb'; database exists","code":"ER_DB_CREATE_EXISTS","errno":1007,"sqlState":"HY000","sqlMessage":"Can't create database 'mydb'; database exists"}
Error: Can't create database 'mydb'; database exists
    at PromiseConnection.query (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\promise.js:92:22)
    at Object.connectAndCreate (C:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBInitializtion.js:239:8)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) 
2020-04-16 16:52:36.606 INFO  CinemaSystem - initCinemaSystem - connectAndCreate - Database Error: Cannot complete action.
Error ID: 2ed0xe2ck92tpk3j 
2020-04-16 16:52:56.769 ERROR 2ed0xe6sk92tpznm - DBInitialization - connectAndCreate - mydb, admin - Can't create database 'mydb'; database exists
{"message":"Can't create database 'mydb'; database exists","code":"ER_DB_CREATE_EXISTS","errno":1007,"sqlState":"HY000","sqlMessage":"Can't create database 'mydb'; database exists"}
Error: Can't create database 'mydb'; database exists
    at PromiseConnection.query (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\promise.js:92:22)
    at Object.connectAndCreate (C:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBInitializtion.js:239:8)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) 
2020-04-16 16:52:56.769 INFO  CinemaSystem - initCinemaSystem - connectAndCreate - Database Error: Cannot complete action.
Error ID: 2ed0xe6sk92tpznm 
2020-04-16 16:56:11.151 ERROR 2ed0x5e4k92tu5n4 - DBInitialization - connectAndCreate - mydb, admin - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IF NOT EXISTS] mydb' at line 1
{"message":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IF NOT EXISTS] mydb' at line 1","code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IF NOT EXISTS] mydb' at line 1"}
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IF NOT EXISTS] mydb' at line 1
    at PromiseConnection.query (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\promise.js:92:22)
    at Object.connectAndCreate (C:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBInitializtion.js:239:8)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) 
2020-04-16 16:56:11.151 INFO  CinemaSystem - initCinemaSystem - connectAndCreate - Database Error: Cannot complete action.
Error ID: 2ed0x5e4k92tu5n4 
2020-04-16 16:56:30.265 ERROR 2ed0x354k92tuke2 - DBManager - singleAdd - general_purpose_daily_report, {"date":"2020-04-15","additionalProps":[[],{}]} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"2020-04-15 00:00:00","origin":"DB","instance":{"date":"2020-04-15T00:00:00.000Z","additionalProps":[[],{}],"updatedAt":"2020-04-16T13:56:30.252Z","createdAt":"2020-04-16T13:56:30.252Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"2020-04-15 00:00:00"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2020-04-15 00:00:00' for key 'PRIMARY'","sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);","parameters":["2020-04-15 00:00:00","[[],{}]","2020-04-16 13:56:30","2020-04-16 13:56:30"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2020-04-15 00:00:00' for key 'PRIMARY'","sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);","parameters":["2020-04-15 00:00:00","[[],{}]","2020-04-16 13:56:30","2020-04-16 13:56:30"]},"sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 16:56:30.275 ERROR 2ed0x354k92tukeb - DBManager - singleAdd - user, {"id":0,"username":"admin","password":"d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892","permissions":"ADMIN"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"0","origin":"DB","instance":{"isUserRemoved":null,"id":0,"username":"admin","password":"d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892","permissions":"ADMIN","updatedAt":"2020-04-16T13:56:30.271Z","createdAt":"2020-04-16T13:56:30.271Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"0"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"admin","d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892","ADMIN",null,"2020-04-16 13:56:30","2020-04-16 13:56:30"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"admin","d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892","ADMIN",null,"2020-04-16 13:56:30","2020-04-16 13:56:30"]},"sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 16:56:30.275 INFO  CinemaSystem - initCinemaSystem - initUser -Database Error: Unique constraint is violated in the database.
Error ID: 2ed0x354k92tukeb 
2020-04-16 16:56:34.156 ERROR 2ed0xcr0k92tune5 - DBManager - singleAdd - general_purpose_daily_report, {"date":"2020-04-15","additionalProps":[[],{}]} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"2020-04-15 00:00:00","origin":"DB","instance":{"date":"2020-04-15T00:00:00.000Z","additionalProps":[[],{}],"updatedAt":"2020-04-16T13:56:34.144Z","createdAt":"2020-04-16T13:56:34.144Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"2020-04-15 00:00:00"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2020-04-15 00:00:00' for key 'PRIMARY'","sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);","parameters":["2020-04-15 00:00:00","[[],{}]","2020-04-16 13:56:34","2020-04-16 13:56:34"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2020-04-15 00:00:00' for key 'PRIMARY'","sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);","parameters":["2020-04-15 00:00:00","[[],{}]","2020-04-16 13:56:34","2020-04-16 13:56:34"]},"sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 16:56:34.166 ERROR 2ed0xcr0k92tunee - DBManager - singleAdd - user, {"id":0,"username":"admin","password":"d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892","permissions":"ADMIN"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"0","origin":"DB","instance":{"isUserRemoved":null,"id":0,"username":"admin","password":"d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892","permissions":"ADMIN","updatedAt":"2020-04-16T13:56:34.162Z","createdAt":"2020-04-16T13:56:34.162Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"0"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"admin","d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892","ADMIN",null,"2020-04-16 13:56:34","2020-04-16 13:56:34"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"admin","d82494f05d6917ba02f7aaa29689ccb444bb73f20380876cb05d1f37537b7892","ADMIN",null,"2020-04-16 13:56:34","2020-04-16 13:56:34"]},"sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 16:56:34.167 INFO  CinemaSystem - initCinemaSystem - initUser -Database Error: Unique constraint is violated in the database.
Error ID: 2ed0xcr0k92tunee 
2020-04-16 17:06:10.835 ERROR 2ed0x18sk92u70cz - DBManager - singleAdd - general_purpose_daily_report, {"date":"2020-04-15","additionalProps":[[],{}]} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"2020-04-15 00:00:00","origin":"DB","instance":{"date":"2020-04-15T00:00:00.000Z","additionalProps":[[],{}],"updatedAt":"2020-04-16T14:06:10.803Z","createdAt":"2020-04-16T14:06:10.803Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"2020-04-15 00:00:00"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2020-04-15 00:00:00' for key 'PRIMARY'","sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);","parameters":["2020-04-15 00:00:00","[[],{}]","2020-04-16 14:06:10","2020-04-16 14:06:10"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '2020-04-15 00:00:00' for key 'PRIMARY'","sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);","parameters":["2020-04-15 00:00:00","[[],{}]","2020-04-16 14:06:10","2020-04-16 14:06:10"]},"sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:06:10.845 ERROR 2ed0x18sk92u70d9 - DBManager - singleAdd - user, {"id":0,"username":"manager","password":"manager","permissions":"MANAGER"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"0","origin":"DB","instance":{"isUserRemoved":null,"id":0,"username":"manager","password":"manager","permissions":"MANAGER","updatedAt":"2020-04-16T14:06:10.840Z","createdAt":"2020-04-16T14:06:10.840Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"0"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"manager","manager","MANAGER",null,"2020-04-16 14:06:10","2020-04-16 14:06:10"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"manager","manager","MANAGER",null,"2020-04-16 14:06:10","2020-04-16 14:06:10"]},"sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:06:10.852 ERROR 2ed0x18sk92u70dg - DBManager - singleAdd - employee, {"id":0,"firstName":"Noa","lastName":"Cohen","contactDetails":"0508888888"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"0","origin":"DB","instance":{"isEmployeeRemoved":null,"id":0,"firstName":"Noa","lastName":"Cohen","contactDetails":"0508888888","updatedAt":"2020-04-16T14:06:10.847Z","createdAt":"2020-04-16T14:06:10.847Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"0"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"Noa","Cohen","0508888888",null,"2020-04-16 14:06:10","2020-04-16 14:06:10"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"Noa","Cohen","0508888888",null,"2020-04-16 14:06:10","2020-04-16 14:06:10"]},"sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:06:10.863 ERROR 2ed0x18sk92u70dr - DBManager - singleAdd - user, {"id":1,"username":"manager","password":"manager","permissions":"MANAGER"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"1","origin":"DB","instance":{"isUserRemoved":null,"id":1,"username":"manager","password":"manager","permissions":"MANAGER","updatedAt":"2020-04-16T14:06:10.854Z","createdAt":"2020-04-16T14:06:10.854Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"1"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '1' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"manager","manager","MANAGER",null,"2020-04-16 14:06:10","2020-04-16 14:06:10"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '1' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"manager","manager","MANAGER",null,"2020-04-16 14:06:10","2020-04-16 14:06:10"]},"sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:06:10.878 ERROR 2ed0x18sk92u70e6 - DBManager - singleAdd - employee, {"id":1,"firstName":"Noa","lastName":"Cohen","contactDetails":"0508888888"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"1","origin":"DB","instance":{"isEmployeeRemoved":null,"id":1,"firstName":"Noa","lastName":"Cohen","contactDetails":"0508888888","updatedAt":"2020-04-16T14:06:10.865Z","createdAt":"2020-04-16T14:06:10.865Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"1"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '1' for key 'PRIMARY'","sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"Noa","Cohen","0508888888",null,"2020-04-16 14:06:10","2020-04-16 14:06:10"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '1' for key 'PRIMARY'","sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"Noa","Cohen","0508888888",null,"2020-04-16 14:06:10","2020-04-16 14:06:10"]},"sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:06:11.606 ERROR 2ed0x18sk92u70ye - DBManager - singleGetById - employee, {} - Unknown database 'mydbtest'
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'mydbtest'","sql":"SELECT `id`, `firstName`, `lastName`, `contactDetails`, `isEmployeeRemoved`, `createdAt`, `updatedAt` FROM `employees` AS `employee` LIMIT 1;"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'mydbtest'","sql":"SELECT `id`, `firstName`, `lastName`, `contactDetails`, `isEmployeeRemoved`, `createdAt`, `updatedAt` FROM `employees` AS `employee` LIMIT 1;"},"sql":"SELECT `id`, `firstName`, `lastName`, `contactDetails`, `isEmployeeRemoved`, `createdAt`, `updatedAt` FROM `employees` AS `employee` LIMIT 1;"}
SequelizeDatabaseError: Unknown database 'mydbtest'
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:244:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:10:23.114 ERROR 2ed0xcvok92ucf0r - DBManager - singleGetById - users, {"id":0} - Cannot read property 'findOne' of undefined
{}
TypeError: Cannot read property 'findOne' of undefined
    at C:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBManager.js:205:27
    at C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:1106:21
    at tryCatcher (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-16 17:10:23.117 INFO  CinemaSystem - initCinemaSystem - isAdminExists -Database Error: Cannot complete action.
Error ID: 2ed0xcvok92ucf0r 
2020-04-16 17:14:32.161 ERROR 2ed0x34ck92uhr6q - DBInitialization - connectAndCreate - mydb, admin - connect ECONNREFUSED 127.0.0.1:3306
{"message":"connect ECONNREFUSED 127.0.0.1:3306","code":"ECONNREFUSED","errno":"ECONNREFUSED"}
Error: connect ECONNREFUSED 127.0.0.1:3306
    at PromiseConnection.query (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\promise.js:92:22)
    at Object.connectAndCreate (C:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBInitializtion.js:244:8)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) 
2020-04-16 17:14:32.162 INFO  CinemaSystem - initCinemaSystem - connectAndCreate - Database Error: Cannot complete action.
Error ID: 2ed0x34ck92uhr6q 
2020-04-16 17:34:10.535 ERROR 2ed0x8kwk92v70fc - DBInitialization - connectAndCreate - mydb, admin - connect ECONNREFUSED 127.0.0.1:3306
{"message":"connect ECONNREFUSED 127.0.0.1:3306","code":"ECONNREFUSED","errno":"ECONNREFUSED"}
Error: connect ECONNREFUSED 127.0.0.1:3306
    at PromiseConnection.query (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\promise.js:92:22)
    at Object.connectAndCreate (C:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBInitializtion.js:244:8)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) 
2020-04-16 17:34:10.535 INFO  CinemaSystem - initCinemaSystem - connectAndCreate - Database Error: Cannot complete action.
Error ID: 2ed0x8kwk92v70fc 
2020-04-16 17:34:21.963 ERROR 2ed0x2d0k92v798s - DBInitialization - connectAndCreate - mydb, admin - connect ECONNREFUSED 127.0.0.1:3306
{"message":"connect ECONNREFUSED 127.0.0.1:3306","code":"ECONNREFUSED","errno":"ECONNREFUSED"}
Error: connect ECONNREFUSED 127.0.0.1:3306
    at PromiseConnection.query (C:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\promise.js:92:22)
    at Object.connectAndCreate (C:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBInitializtion.js:244:8)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) 
2020-04-16 17:34:21.963 INFO  CinemaSystem - initCinemaSystem - connectAndCreate - Database Error: Cannot complete action.
Error ID: 2ed0x2d0k92v798s 
2020-04-16 17:37:50.601 ERROR 2ed0x7ggk92vbq8a - DBManager - singleGetById - incomes_daily_report, {"date":"2020-04-16T00:00:00.000Z"} - Table 'mydbtest.incomes_daily_reports' doesn't exist
{"name":"SequelizeDatabaseError","parent":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'mydbtest.incomes_daily_reports' doesn't exist","sql":"SELECT `date`, `creatorEmployeeId`, `numOfTabsSales`, `cafeteriaCashRevenues`, `cafeteriaCreditCardRevenues`, `ticketsCashRevenues`, `ticketsCreditCardRevenues`, `tabsCashRevenues`, `tabsCreditCardRevenues`, `createdAt`, `updatedAt` FROM `incomes_daily_reports` AS `incomes_daily_report` WHERE `incomes_daily_report`.`date` = '2020-04-16 00:00:00' LIMIT 1;"},"original":{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'mydbtest.incomes_daily_reports' doesn't exist","sql":"SELECT `date`, `creatorEmployeeId`, `numOfTabsSales`, `cafeteriaCashRevenues`, `cafeteriaCreditCardRevenues`, `ticketsCashRevenues`, `ticketsCreditCardRevenues`, `tabsCashRevenues`, `tabsCreditCardRevenues`, `createdAt`, `updatedAt` FROM `incomes_daily_reports` AS `incomes_daily_report` WHERE `incomes_daily_report`.`date` = '2020-04-16 00:00:00' LIMIT 1;"},"sql":"SELECT `date`, `creatorEmployeeId`, `numOfTabsSales`, `cafeteriaCashRevenues`, `cafeteriaCreditCardRevenues`, `ticketsCashRevenues`, `ticketsCreditCardRevenues`, `tabsCashRevenues`, `tabsCreditCardRevenues`, `createdAt`, `updatedAt` FROM `incomes_daily_reports` AS `incomes_daily_report` WHERE `incomes_daily_report`.`date` = '2020-04-16 00:00:00' LIMIT 1;"}
SequelizeDatabaseError: Table 'mydbtest.incomes_daily_reports' doesn't exist
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:244:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:38:00.605 ERROR 2ed0x7ggk92vbxy5 - DBManager - singleGetById - general_purpose_daily_report, {"date":"2020-04-16T00:00:00.000Z"} - ConnectionManager.getConnection was called after the connection manager was closed!
{}
Error: ConnectionManager.getConnection was called after the connection manager was closed!
    at ConnectionManager.getConnection (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:113:29)
    at Transaction.prepareEnvironment (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\transaction.js:121:60)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:1105:26
    at Function._clsRun (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:1150:21)
    at Sequelize.transaction (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:1104:22)
    at Function.singleGetById (c:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBManager.js:204:10)
    at Array.testAddGeneralPurposeDailyReport (c:\Users\ASUS\Documents\GitHub\negative-app\spec\support\DBtests\ReportsTests.spec.js:76:18)
    at Timeout._onTimeout (c:\Users\ASUS\Documents\GitHub\negative-app\spec\support\test\ReportsOperationsTests.spec.js:152:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) 
2020-04-16 17:39:17.658 ERROR 2ed0x2ywk92vdlej - DBManager - singleAdd - employee, {"id":1,"firstName":"Noa","lastName":"Cohen","contactDetails":"0508888888"} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`employees`, CONSTRAINT `employees_ibfk_1` FOREIGN KEY (`id`) REFERENCES `users` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`employees`, CONSTRAINT `employees_ibfk_1` FOREIGN KEY (`id`) REFERENCES `users` (`id`))","sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"Noa","Cohen","0508888888",null,"2020-04-16 14:39:17","2020-04-16 14:39:17"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`employees`, CONSTRAINT `employees_ibfk_1` FOREIGN KEY (`id`) REFERENCES `users` (`id`))","sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"Noa","Cohen","0508888888",null,"2020-04-16 14:39:17","2020-04-16 14:39:17"]},"sql":"INSERT INTO `employees` (`id`,`firstName`,`lastName`,`contactDetails`,`isEmployeeRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"Noa","Cohen","0508888888",null,"2020-04-16 14:39:17","2020-04-16 14:39:17"],"fields":["id"],"table":"users","value":1,"index":"employees_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`employees`, CONSTRAINT `employees_ibfk_1` FOREIGN KEY (`id`) REFERENCES `users` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:39:31.857 ERROR 2ed0x3zwk92vdwcy - DBManager - singleAdd - general_purpose_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"additionalProps":[["Cash counted"],{"Cash counted":"true"}]} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`general_purpose_daily_reports`, CONSTRAINT `general_purpose_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`general_purpose_daily_reports`, CONSTRAINT `general_purpose_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`creatorEmployeeId`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,"[[\"Cash counted\"],{\"Cash counted\":\"true\"}]","2020-04-16 14:39:31","2020-04-16 14:39:31"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`general_purpose_daily_reports`, CONSTRAINT `general_purpose_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`creatorEmployeeId`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,"[[\"Cash counted\"],{\"Cash counted\":\"true\"}]","2020-04-16 14:39:31","2020-04-16 14:39:31"]},"sql":"INSERT INTO `general_purpose_daily_reports` (`date`,`creatorEmployeeId`,`additionalProps`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,"[[\"Cash counted\"],{\"Cash counted\":\"true\"}]","2020-04-16 14:39:31","2020-04-16 14:39:31"],"fields":["creatorEmployeeId"],"table":"employees","index":"general_purpose_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`general_purpose_daily_reports`, CONSTRAINT `general_purpose_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:39:48.761 ERROR 2ed0x3zwk92ve9eh - DBManager - singleAdd - inventory_daily_report, {"date":"2020-03-01T22:00:00.000Z","productId":0,"creatorEmployeeId":0,"quantitySold":3,"quantityInStock":7,"stockThrown":7} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_2` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_2` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:48","2020-04-16 14:39:48"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_2` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:48","2020-04-16 14:39:48"]},"sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:48","2020-04-16 14:39:48"],"fields":["creatorEmployeeId"],"table":"employees","index":"inventory_daily_reports_ibfk_2","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_2` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:39:52.645 ERROR 2ed0x3zwk92veced - DBManager - singleAdd - movie_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"movieId":0,"theater":4,"numOfTicketsSales":30,"numOfUsedTickets":25,"wasAirConditionGlitches":false} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:39:52","2020-04-16 14:39:52"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:39:52","2020-04-16 14:39:52"]},"sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:39:52","2020-04-16 14:39:52"],"fields":["creatorEmployeeId"],"table":"employees","index":"movie_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:39:52.692 ERROR 2ed0x3zwk92vecfo - DBManager - singleAdd - movie_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"movieId":0,"theater":4,"numOfTicketsSales":30,"numOfUsedTickets":25,"wasAirConditionGlitches":false} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:39:52","2020-04-16 14:39:52"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:39:52","2020-04-16 14:39:52"]},"sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:39:52","2020-04-16 14:39:52"],"fields":["creatorEmployeeId"],"table":"employees","index":"movie_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:39:55.886 ERROR 2ed0x3zwk92veewe - DBManager - singleAdd - inventory_daily_report, {"date":"2020-03-01T22:00:00.000Z","productId":0,"creatorEmployeeId":0,"quantitySold":3,"quantityInStock":7,"stockThrown":7} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:55","2020-04-16 14:39:55"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:55","2020-04-16 14:39:55"]},"sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:55","2020-04-16 14:39:55"],"fields":["productId"],"table":"cafeteria_products","index":"inventory_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:39:56.421 ERROR 2ed0x3zwk92vefb9 - DBManager - singleAdd - inventory_daily_report, {"date":"2020-03-01T22:00:00.000Z","productId":0,"creatorEmployeeId":0,"quantitySold":3,"quantityInStock":7,"stockThrown":7} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:56","2020-04-16 14:39:56"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:56","2020-04-16 14:39:56"]},"sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:39:56","2020-04-16 14:39:56"],"fields":["productId"],"table":"cafeteria_products","index":"inventory_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:40:03.726 ERROR 2ed0x3zwk92veky6 - DBManager - singleAdd - movie_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"movieId":0,"theater":4,"numOfTicketsSales":30,"numOfUsedTickets":25,"wasAirConditionGlitches":false} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:40:03","2020-04-16 14:40:03"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:40:03","2020-04-16 14:40:03"]},"sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:40:03","2020-04-16 14:40:03"],"fields":["creatorEmployeeId"],"table":"employees","index":"movie_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:40:07.121 ERROR 2ed0x3zwk92venkh - DBManager - singleAdd - incomes_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"numOfTabsSales":0,"cafeteriaCashRevenues":20,"cafeteriaCreditCardRevenues":20,"ticketsCashRevenues":20,"ticketsCreditCardRevenues":20,"tabsCashRevenues":20,"tabsCreditCardRevenues":20} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:40:07","2020-04-16 14:40:07"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:40:07","2020-04-16 14:40:07"]},"sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:40:07","2020-04-16 14:40:07"],"fields":["creatorEmployeeId"],"table":"employees","index":"incomes_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:40:09.933 ERROR 2ed0x3zwk92vepql - DBManager - singleAdd - incomes_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"numOfTabsSales":0,"cafeteriaCashRevenues":20,"cafeteriaCreditCardRevenues":20,"ticketsCashRevenues":20,"ticketsCreditCardRevenues":20,"tabsCashRevenues":20,"tabsCreditCardRevenues":20} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:40:09","2020-04-16 14:40:09"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:40:09","2020-04-16 14:40:09"]},"sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:40:09","2020-04-16 14:40:09"],"fields":["creatorEmployeeId"],"table":"employees","index":"incomes_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:41:34.864 ERROR 2ed0x73kk92vgj9t - DBManager - singleAdd - cafeteria_product, {"id":0,"name":"Coke","categoryId":0,"price":5.9,"quantity":20,"maxQuantity":45,"minQuantity":10} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`cafeteria_products`, CONSTRAINT `cafeteria_products_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`cafeteria_products`, CONSTRAINT `cafeteria_products_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))","sql":"INSERT INTO `cafeteria_products` (`id`,`name`,`categoryId`,`price`,`quantity`,`maxQuantity`,`minQuantity`,`isProductRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[0,"Coke",0,5.9,20,45,10,null,"2020-04-16 14:41:34","2020-04-16 14:41:34"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`cafeteria_products`, CONSTRAINT `cafeteria_products_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))","sql":"INSERT INTO `cafeteria_products` (`id`,`name`,`categoryId`,`price`,`quantity`,`maxQuantity`,`minQuantity`,`isProductRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[0,"Coke",0,5.9,20,45,10,null,"2020-04-16 14:41:34","2020-04-16 14:41:34"]},"sql":"INSERT INTO `cafeteria_products` (`id`,`name`,`categoryId`,`price`,`quantity`,`maxQuantity`,`minQuantity`,`isProductRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[0,"Coke",0,5.9,20,45,10,null,"2020-04-16 14:41:34","2020-04-16 14:41:34"],"fields":["categoryId"],"table":"categories","index":"cafeteria_products_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`cafeteria_products`, CONSTRAINT `cafeteria_products_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:41:38.546 ERROR 2ed0x73kk92vgm42 - DBManager - singleAdd - movie, {"id":0,"name":"Spiderman","categoryId":0} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movies`, CONSTRAINT `movies_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movies`, CONSTRAINT `movies_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))","sql":"INSERT INTO `movies` (`id`,`name`,`categoryId`,`movieKey`,`examinationRoom`,`isMovieRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":[0,"Spiderman",0,null,null,null,"2020-04-16 14:41:38","2020-04-16 14:41:38"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movies`, CONSTRAINT `movies_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))","sql":"INSERT INTO `movies` (`id`,`name`,`categoryId`,`movieKey`,`examinationRoom`,`isMovieRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":[0,"Spiderman",0,null,null,null,"2020-04-16 14:41:38","2020-04-16 14:41:38"]},"sql":"INSERT INTO `movies` (`id`,`name`,`categoryId`,`movieKey`,`examinationRoom`,`isMovieRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":[0,"Spiderman",0,null,null,null,"2020-04-16 14:41:38","2020-04-16 14:41:38"],"fields":["categoryId"],"table":"categories","index":"movies_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movies`, CONSTRAINT `movies_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:41:49.500 ERROR 2ed0x73kk92vgukc - DBManager - singleUpdate - category, {"id":0}, {"isCategoryRemoved":"2020-04-16T14:41:49.444Z"} - rollback has been called on this transaction(28bbb828-0ddd-4bc6-b930-5783d24b903a), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
{"sql":"UPDATE `categories` SET `isCategoryRemoved`=?,`updatedAt`=? WHERE `id` = ?"}
Error: rollback has been called on this transaction(28bbb828-0ddd-4bc6-b930-5783d24b903a), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:623:25)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:636:9
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:53
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:60:10)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:30
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at Sequelize.query (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:580:23)
    at QueryInterface.bulkUpdate (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1044:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:3222:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5) 
2020-04-16 17:43:16.717 ERROR 2ed0x9lgk92vipv2 - DBManager - singleRemove - movie_order, {"orderId":0} - rollback has been called on this transaction(867767a5-cb64-4d3c-b735-427087372684), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
{"sql":"DELETE FROM `movie_orders` WHERE `orderId` = 0"}
Error: rollback has been called on this transaction(867767a5-cb64-4d3c-b735-427087372684), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:623:25)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:636:9
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:53
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:60:10)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:30
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at Sequelize.query (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:580:23)
    at QueryInterface.bulkDelete (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1112:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:2946:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5) 
2020-04-16 17:43:16.727 ERROR 2ed0x9lgk92vipvb - DBManager - singleRemove - cafeteria_product_order, {"orderId":0} - rollback has been called on this transaction(e268a12f-1103-43f4-9234-cdcfb650ef8e), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
{"sql":"DELETE FROM `cafeteria_product_orders` WHERE `orderId` = 0"}
Error: rollback has been called on this transaction(e268a12f-1103-43f4-9234-cdcfb650ef8e), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:623:25)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:636:9
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:53
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:60:10)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:30
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at Sequelize.query (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:580:23)
    at QueryInterface.bulkDelete (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1112:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:2946:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5) 
2020-04-16 17:43:16.735 ERROR 2ed0x9lgk92vipvj - DBManager - singleRemove - order, {"id":0} - rollback has been called on this transaction(b7edde5c-7a2d-41a2-abd5-3efa8aeb9d5f), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
{"sql":"DELETE FROM `orders` WHERE `id` = 0"}
Error: rollback has been called on this transaction(b7edde5c-7a2d-41a2-abd5-3efa8aeb9d5f), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:623:25)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:636:9
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:53
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:60:10)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:30
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at Sequelize.query (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:580:23)
    at QueryInterface.bulkDelete (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1112:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:2946:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5) 
2020-04-16 17:43:20.011 ERROR 2ed0x9lgk92visej - DBManager - singleAdd - order, {"id":0,"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"supplierId":0} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`orders`, CONSTRAINT `orders_ibfk_3` FOREIGN KEY (`supplierId`) REFERENCES `suppliers` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`orders`, CONSTRAINT `orders_ibfk_3` FOREIGN KEY (`supplierId`) REFERENCES `suppliers` (`id`))","sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-03-01 22:00:00",0,null,0,"2020-04-16 14:43:19","2020-04-16 14:43:19"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`orders`, CONSTRAINT `orders_ibfk_3` FOREIGN KEY (`supplierId`) REFERENCES `suppliers` (`id`))","sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-03-01 22:00:00",0,null,0,"2020-04-16 14:43:19","2020-04-16 14:43:19"]},"sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-03-01 22:00:00",0,null,0,"2020-04-16 14:43:19","2020-04-16 14:43:19"],"fields":["supplierId"],"table":"suppliers","index":"orders_ibfk_3","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`orders`, CONSTRAINT `orders_ibfk_3` FOREIGN KEY (`supplierId`) REFERENCES `suppliers` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:43:20.058 ERROR 2ed0x9lgk92visfu - DBManager - singleAdd - order, {"id":0,"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":2,"supplierId":0} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-03-01 22:00:00",2,null,0,"2020-04-16 14:43:20","2020-04-16 14:43:20"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-03-01 22:00:00",2,null,0,"2020-04-16 14:43:20","2020-04-16 14:43:20"]},"sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-03-01 22:00:00",2,null,0,"2020-04-16 14:43:20","2020-04-16 14:43:20"],"fields":["creatorEmployeeId"],"table":"employees","value":2,"index":"orders_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:43:30.912 ERROR 2ed0x9lgk92vj0tc - DBManager - singleRemove - order, {"id":0} - rollback has been called on this transaction(e6fab6dc-171e-42c6-b703-dc0d49ea22eb), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
{"sql":"DELETE FROM `orders` WHERE `id` = 0"}
Error: rollback has been called on this transaction(e6fab6dc-171e-42c6-b703-dc0d49ea22eb), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:623:25)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:636:9
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:53
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\retry-as-promised\index.js:60:10)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:631:30
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\method.js:39:29)
    at Sequelize.query (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\sequelize.js:580:23)
    at QueryInterface.bulkDelete (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1112:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:2946:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5) 
2020-04-16 17:46:48.418 ERROR 2ed0xbl8k92vn97n - DBManager - singleAdd - movie, {"id":0,"name":"Spiderman","categoryId":1} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movies`, CONSTRAINT `movies_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movies`, CONSTRAINT `movies_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))","sql":"INSERT INTO `movies` (`id`,`name`,`categoryId`,`movieKey`,`examinationRoom`,`isMovieRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":[0,"Spiderman",1,null,null,null,"2020-04-16 14:46:48","2020-04-16 14:46:48"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movies`, CONSTRAINT `movies_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))","sql":"INSERT INTO `movies` (`id`,`name`,`categoryId`,`movieKey`,`examinationRoom`,`isMovieRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":[0,"Spiderman",1,null,null,null,"2020-04-16 14:46:48","2020-04-16 14:46:48"]},"sql":"INSERT INTO `movies` (`id`,`name`,`categoryId`,`movieKey`,`examinationRoom`,`isMovieRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":[0,"Spiderman",1,null,null,null,"2020-04-16 14:46:48","2020-04-16 14:46:48"],"fields":["categoryId"],"table":"categories","value":1,"index":"movies_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movies`, CONSTRAINT `movies_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:46:51.892 ERROR 2ed0xbl8k92vnbw4 - DBManager - singleAdd - user, {"id":0,"username":"admin","password":"admin","permissions":"ADMIN"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"0","origin":"DB","instance":{"isUserRemoved":null,"id":0,"username":"admin","password":"admin","permissions":"ADMIN","updatedAt":"2020-04-16T14:46:51.888Z","createdAt":"2020-04-16T14:46:51.888Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"0"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"admin","admin","ADMIN",null,"2020-04-16 14:46:51","2020-04-16 14:46:51"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"admin","admin","ADMIN",null,"2020-04-16 14:46:51","2020-04-16 14:46:51"]},"sql":"INSERT INTO `users` (`id`,`username`,`password`,`permissions`,`isUserRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:46:52.450 ERROR 2ed0xbl8k92vncbm - DBInitialization - connectAndCreate - mydbTest, lalala - Access denied for user 'root'@'localhost' (using password: YES)
{"message":"Access denied for user 'root'@'localhost' (using password: YES)","code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: YES)"}
Error: Access denied for user 'root'@'localhost' (using password: YES)
    at PromiseConnection.query (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\promise.js:92:22)
    at Object.connectAndCreate (c:\Users\ASUS\Documents\GitHub\negative-app\server\src\main\DataLayer\DBInitializtion.js:244:8)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) 
2020-04-16 17:46:52.455 ERROR 2ed0xbl8k92vncbr - DBInitialization - initDB - authenticate - mydbTest, admin - Unknown database 'mydbtest'
{"name":"SequelizeConnectionError","parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'mydbtest'"},"original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'mydbtest'"}}
SequelizeConnectionError: Unknown database 'mydbtest'
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:133:19
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-16 17:47:20.035 ERROR 2ed0xcmsk92vnxlw - DBManager - singleAdd - inventory_daily_report, {"date":"2020-03-01T22:00:00.000Z","productId":0,"creatorEmployeeId":0,"quantitySold":3,"quantityInStock":7,"stockThrown":7} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:47:20","2020-04-16 14:47:20"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:47:20","2020-04-16 14:47:20"]},"sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:47:20","2020-04-16 14:47:20"],"fields":["productId"],"table":"cafeteria_products","index":"inventory_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:47:20.081 ERROR 2ed0xcmsk92vnxn5 - DBManager - singleAdd - inventory_daily_report, {"date":"2020-03-01T22:00:00.000Z","productId":0,"creatorEmployeeId":0,"quantitySold":3,"quantityInStock":7,"stockThrown":7} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:47:20","2020-04-16 14:47:20"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))","sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:47:20","2020-04-16 14:47:20"]},"sql":"INSERT INTO `inventory_daily_reports` (`date`,`productId`,`creatorEmployeeId`,`quantitySold`,`quantityInStock`,`stockThrown`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,3,7,7,"2020-04-16 14:47:20","2020-04-16 14:47:20"],"fields":["productId"],"table":"cafeteria_products","index":"inventory_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`inventory_daily_reports`, CONSTRAINT `inventory_daily_reports_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `cafeteria_products` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:47:37.880 ERROR 2ed0xcmsk92vobdj - DBManager - singleAdd - incomes_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"numOfTabsSales":0,"cafeteriaCashRevenues":20,"cafeteriaCreditCardRevenues":20,"ticketsCashRevenues":20,"ticketsCreditCardRevenues":20,"tabsCashRevenues":20,"tabsCreditCardRevenues":20} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:47:37","2020-04-16 14:47:37"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:47:37","2020-04-16 14:47:37"]},"sql":"INSERT INTO `incomes_daily_reports` (`date`,`creatorEmployeeId`,`numOfTabsSales`,`cafeteriaCashRevenues`,`cafeteriaCreditCardRevenues`,`ticketsCashRevenues`,`ticketsCreditCardRevenues`,`tabsCashRevenues`,`tabsCreditCardRevenues`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,20,20,20,20,20,20,"2020-04-16 14:47:37","2020-04-16 14:47:37"],"fields":["creatorEmployeeId"],"table":"employees","index":"incomes_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`incomes_daily_reports`, CONSTRAINT `incomes_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:48:55.361 ERROR 2ed0xcmsk92vpz5t - DBManager - singleAdd - movie_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"movieId":0,"theater":4,"numOfTicketsSales":30,"numOfUsedTickets":25,"wasAirConditionGlitches":false} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:48:55","2020-04-16 14:48:55"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:48:55","2020-04-16 14:48:55"]},"sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:48:55","2020-04-16 14:48:55"],"fields":["creatorEmployeeId"],"table":"employees","index":"movie_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-16 17:48:55.403 ERROR 2ed0xcmsk92vpz6z - DBManager - singleAdd - movie_daily_report, {"date":"2020-03-01T22:00:00.000Z","creatorEmployeeId":0,"movieId":0,"theater":4,"numOfTicketsSales":30,"numOfUsedTickets":25,"wasAirConditionGlitches":false} - Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:48:55","2020-04-16 14:48:55"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:48:55","2020-04-16 14:48:55"]},"sql":"INSERT INTO `movie_daily_reports` (`date`,`creatorEmployeeId`,`movieId`,`theater`,`numOfTicketsSales`,`numOfUsedTickets`,`wasAirConditionGlitches`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?);","parameters":["2020-03-01 22:00:00",0,0,4,30,25,false,"2020-04-16 14:48:55","2020-04-16 14:48:55"],"fields":["creatorEmployeeId"],"table":"employees","index":"movie_daily_reports_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`mydbtest`.`movie_daily_reports`, CONSTRAINT `movie_daily_reports_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 11:20:10.119 ERROR 2ed0xiukk9chwzyg - DBManager - executeActions  - add, , {"element":{"id":0,"date":"2020-04-23","creatorEmployeeId":0,"supplierId":0}} - Cannot add or update a child row: a foreign key constraint fails (`ordertest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`ordertest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-04-23 00:00:00",0,null,0,"2020-04-23 08:20:10","2020-04-23 08:20:10"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`ordertest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-04-23 00:00:00",0,null,0,"2020-04-23 08:20:10","2020-04-23 08:20:10"]},"sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[0,"2020-04-23 00:00:00",0,null,0,"2020-04-23 08:20:10","2020-04-23 08:20:10"],"fields":["creatorEmployeeId"],"table":"employees","index":"orders_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`ordertest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 11:20:10.120 INFO  InventoryManagemnt - addMovieOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xiukk9chwzyg 
2020-04-23 11:40:18.518 ERROR 2ed0xh5sk9cimwd3 - DBManager - singleGetById - order, {} - WHERE parameter "id" has invalid "undefined" value
{}
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1315:28)
    at QueryInterface.select (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1122:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:1757:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 11:41:50.918 ERROR 2ed0xf9ok9ciovnr - DBManager - singleAdd - category, {"id":0,"name":"categoryTest"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"0","origin":"DB","instance":{"parentId":-1,"isCategoryRemoved":null,"id":0,"name":"categoryTest","updatedAt":"2020-04-23T08:41:50.911Z","createdAt":"2020-04-23T08:41:50.911Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"0"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `categories` (`id`,`parentId`,`name`,`isCategoryRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?);","parameters":[0,-1,"categoryTest",null,"2020-04-23 08:41:50","2020-04-23 08:41:50"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '0' for key 'PRIMARY'","sql":"INSERT INTO `categories` (`id`,`parentId`,`name`,`isCategoryRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?);","parameters":[0,-1,"categoryTest",null,"2020-04-23 08:41:50","2020-04-23 08:41:50"]},"sql":"INSERT INTO `categories` (`id`,`parentId`,`name`,`isCategoryRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 11:41:50.964 ERROR 2ed0xf9ok9ciovp0 - DBManager - singleAdd - category, {"id":1,"name":"categoryTest"} - Validation error
{"name":"SequelizeUniqueConstraintError","errors":[{"message":"PRIMARY must be unique","type":"unique violation","path":"PRIMARY","value":"1","origin":"DB","instance":{"parentId":-1,"isCategoryRemoved":null,"id":1,"name":"categoryTest","updatedAt":"2020-04-23T08:41:50.959Z","createdAt":"2020-04-23T08:41:50.959Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"PRIMARY":"1"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '1' for key 'PRIMARY'","sql":"INSERT INTO `categories` (`id`,`parentId`,`name`,`isCategoryRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?);","parameters":[1,-1,"categoryTest",null,"2020-04-23 08:41:50","2020-04-23 08:41:50"]},"original":{"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '1' for key 'PRIMARY'","sql":"INSERT INTO `categories` (`id`,`parentId`,`name`,`isCategoryRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?);","parameters":[1,-1,"categoryTest",null,"2020-04-23 08:41:50","2020-04-23 08:41:50"]},"sql":"INSERT INTO `categories` (`id`,`parentId`,`name`,`isCategoryRemoved`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?);"}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:223:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 11:42:33.994 ERROR 2ed0xf9ok9cipswa - DBManager - singleGetById - order, {} - pool is draining and cannot accept work
{}
Error: pool is draining and cannot accept work
    at Pool.acquire (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize-pool\lib\Pool.js:316:9)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:280:24
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 11:42:38.632 ERROR 2ed0xd70k9cipwh5 - DBManager - singleGetById - order, {} - WHERE parameter "id" has invalid "undefined" value
{}
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1315:28)
    at QueryInterface.select (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1122:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:1757:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 11:43:22.828 ERROR 2ed0x1ask9ciqukt - DBManager - singleGetById - order, {} - pool is draining and cannot accept work
{}
Error: pool is draining and cannot accept work
    at Pool.acquire (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize-pool\lib\Pool.js:316:9)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:280:24
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 11:44:39.688 ERROR 2ed0xdvwk9cishvt - DBManager - singleGetById - order, {} - WHERE parameter "id" has invalid "undefined" value
{}
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1315:28)
    at QueryInterface.select (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1122:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:1757:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 11:44:45.287 ERROR 2ed0x4m0k9cism7c - DBManager - singleGetById - order, {} - WHERE parameter "id" has invalid "undefined" value
{}
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1315:28)
    at QueryInterface.select (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1122:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:1757:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 12:10:22.141 ERROR 2ed0xhvwk9cjpk1q - DBManager - executeActions  - add, , {"where":{"id":0}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_2` FOREIGN KEY (`movieId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_2` FOREIGN KEY (`movieId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_2` FOREIGN KEY (`movieId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"sql":"DELETE FROM `orders` WHERE `id` = 0","fields":["movieId"],"table":"orders","index":"movie_orders_ibfk_2","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_2` FOREIGN KEY (`movieId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:10:22.142 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xhvwk9cjpk1q 
2020-04-23 12:10:22.155 ERROR 2ed0xhvwk9cjpk23 - DBManager - executeActions  - add, , {"where":{"id":1}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_2` FOREIGN KEY (`productId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_2` FOREIGN KEY (`productId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 1"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_2` FOREIGN KEY (`productId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 1"},"sql":"DELETE FROM `orders` WHERE `id` = 1","fields":["productId"],"table":"orders","index":"cafeteria_product_orders_ibfk_2","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_2` FOREIGN KEY (`productId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:10:22.155 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xhvwk9cjpk23 
2020-04-23 12:10:22.177 ERROR 2ed0xhvwk9cjpk2p - DBManager - executeActions  - add, , {"where":{"id":0}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_2` FOREIGN KEY (`movieId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_2` FOREIGN KEY (`movieId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_2` FOREIGN KEY (`movieId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"sql":"DELETE FROM `orders` WHERE `id` = 0","fields":["movieId"],"table":"orders","index":"movie_orders_ibfk_2","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_2` FOREIGN KEY (`movieId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:10:22.178 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xhvwk9cjpk2p 
2020-04-23 12:12:41.995 ERROR 2ed0xidwk9cjsjyk - DBManager - executeActions  - add, , {"where":{"id":0}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"sql":"DELETE FROM `orders` WHERE `id` = 0","fields":["orderId"],"table":"orders","index":"movie_orders_ibfk_1","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:12:41.998 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xidwk9cjsjyk 
2020-04-23 12:12:42.238 ERROR 2ed0xidwk9cjsk59 - DBManager - executeActions  - add, , {"where":{"id":1}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 1"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 1"},"sql":"DELETE FROM `orders` WHERE `id` = 1","fields":["orderId"],"table":"orders","index":"cafeteria_product_orders_ibfk_1","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:12:42.239 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xidwk9cjsk59 
2020-04-23 12:12:42.280 ERROR 2ed0xidwk9cjsk6g - DBManager - executeActions  - add, , {"where":{"id":0}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"sql":"DELETE FROM `orders` WHERE `id` = 0","fields":["orderId"],"table":"orders","index":"movie_orders_ibfk_1","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:12:42.280 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xidwk9cjsk6g 
2020-04-23 12:13:04.201 ERROR 2ed0xjgok9cjt13e - DBManager - executeActions  - add, , {"where":{"id":0}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"sql":"DELETE FROM `orders` WHERE `id` = 0","fields":["orderId"],"table":"orders","index":"movie_orders_ibfk_1","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:13:04.202 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xjgok9cjt13e 
2020-04-23 12:13:04.220 ERROR 2ed0xjgok9cjt13w - DBManager - executeActions  - add, , {"where":{"id":1}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 1"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 1"},"sql":"DELETE FROM `orders` WHERE `id` = 1","fields":["orderId"],"table":"orders","index":"cafeteria_product_orders_ibfk_1","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`cafeteria_product_orders`, CONSTRAINT `cafeteria_product_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:13:04.220 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xjgok9cjt13w 
2020-04-23 12:13:04.246 ERROR 2ed0xjgok9cjt14m - DBManager - executeActions  - add, , {"where":{"id":0}} - Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"original":{"code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlState":"23000","sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))","sql":"DELETE FROM `orders` WHERE `id` = 0"},"sql":"DELETE FROM `orders` WHERE `id` = 0","fields":["orderId"],"table":"orders","index":"movie_orders_ibfk_1","reltype":"parent"}
SequelizeForeignKeyConstraintError: Cannot delete or update a parent row: a foreign key constraint fails (`ordertest`.`movie_orders`, CONSTRAINT `movie_orders_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Query.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:13:04.246 INFO  InventoryManagemnt - removeOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xjgok9cjt14m 
2020-04-23 12:26:25.770 ERROR 2ed0xcwck9cka7l7 - DBManager - singleGetById - order, {} - WHERE parameter "id" has invalid "undefined" value
{}
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1315:28)
    at QueryInterface.select (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1122:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:1757:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 12:26:25.774 ERROR 2ed0xcwck9cka7la - DBManager - singleGetById - order, {} - WHERE parameter "id" has invalid "undefined" value
{}
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1315:28)
    at QueryInterface.select (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1122:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:1757:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 12:40:19.249 ERROR 2ed0xipok9cks2pe - DBManager - executeActions  - add, , {"element":{"id":1,"date":"2020-04-23","creatorEmployeeId":1,"supplierId":0}} - Cannot add or update a child row: a foreign key constraint fails (`ordertest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
{"name":"SequelizeForeignKeyConstraintError","parent":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`ordertest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"2020-04-23 00:00:00",1,null,0,"2020-04-23 09:40:19","2020-04-23 09:40:19"]},"original":{"code":"ER_NO_REFERENCED_ROW_2","errno":1452,"sqlState":"23000","sqlMessage":"Cannot add or update a child row: a foreign key constraint fails (`ordertest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))","sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"2020-04-23 00:00:00",1,null,0,"2020-04-23 09:40:19","2020-04-23 09:40:19"]},"sql":"INSERT INTO `orders` (`id`,`date`,`creatorEmployeeId`,`recipientEmployeeId`,`supplierId`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?);","parameters":[1,"2020-04-23 00:00:00",1,null,0,"2020-04-23 09:40:19","2020-04-23 09:40:19"],"fields":["creatorEmployeeId"],"table":"employees","value":1,"index":"orders_ibfk_1","reltype":"child"}
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`ordertest`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`creatorEmployeeId`) REFERENCES `employees` (`id`))
    at Query.formatError (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:233:16)
    at Execute.handler [as onResult] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) 
2020-04-23 12:40:19.250 INFO  InventoryManagemnt - addCafeteriaOrder - Database Error: Foreign key constraint is violated in the database.
Error ID: 2ed0xipok9cks2pe 
2020-04-23 12:40:19.254 ERROR 2ed0xipok9cks2pi - DBManager - singleGetById - order, {} - WHERE parameter "id" has invalid "undefined" value
{}
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1315:28)
    at QueryInterface.select (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1122:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:1757:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 12:40:19.264 ERROR 2ed0xipok9cks2ps - DBManager - singleGetById - order, {} - WHERE parameter "id" has invalid "undefined" value
{}
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1315:28)
    at QueryInterface.select (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\query-interface.js:1122:27)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\model.js:1757:34
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
2020-04-23 12:41:49.191 ERROR 2ed0xk34k9cku03s - DBManager - singleGetById - movie_order, {"orderId":0,"movieId":0} - pool is draining and cannot accept work
{}
Error: pool is draining and cannot accept work
    at Pool.acquire (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize-pool\lib\Pool.js:316:9)
    at c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:280:24
    at tryCatcher (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (c:\Users\ASUS\Documents\GitHub\negative-app\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) 
